version: "3.8"

services:
  nba-mcp-synthesis:
    build: .
    container_name: nba-mcp-synthesis
    environment:
      - PROJECT_NAME=nba-mcp-synthesis
      - SPORT_NAME=NBA
      - NBA_MCP_CONTEXT=WORKFLOW
      - MCP_TRANSPORT=stdio
    volumes:
      # Mount secrets directory (read-only)
      - /Users/ryanranft/Desktop/++:/secrets:ro
      # Mount logs directory
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - nba-network

  # Optional: Add a secrets management service
  secrets-manager:
    image: alpine:latest
    container_name: secrets-manager
    command: |
      sh -c "
        echo 'Secrets Manager - Monitoring secret files...'
        while true; do
          echo \"[$$(date)] Checking secrets at /secrets\"
          find /secrets -name '*.env' -exec echo \"Found: {}\" \;
          sleep 300
        done
      "
    volumes:
      - /Users/ryanranft/Desktop/++:/secrets:ro
    networks:
      - nba-network
    restart: unless-stopped

networks:
  nba-network:
    driver: bridge

volumes:
  secrets:
    external: true
    name: nba-mcp-secrets

