version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: nba-mcp-jaeger
    ports:
      # Jaeger UI
      - "16686:16686"
      # Jaeger collector HTTP
      - "14268:14268"
      # Jaeger collector gRPC
      - "14250:14250"
      # Jaeger agent (Thrift compact)
      - "6831:6831/udp"
      # Jaeger agent (Thrift binary)
      - "6832:6832/udp"
      # Zipkin compatible endpoint
      - "9411:9411"
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - SPAN_STORAGE_TYPE=badger
      - BADGER_EPHEMERAL=false
      - BADGER_DIRECTORY_VALUE=/badger/data
      - BADGER_DIRECTORY_KEY=/badger/key
    volumes:
      - jaeger-badger:/badger
    restart: unless-stopped
    networks:
      - nba-mcp-network

volumes:
  jaeger-badger:

networks:
  nba-mcp-network:
    driver: bridge
