apiVersion: v1
kind: Secret
metadata:
  name: nba-mcp-synthesis-secrets
  namespace: nba-mcp-synthesis
  labels:
    app: nba-mcp-synthesis
    environment: production
    project: nba-mcp-synthesis
    sport: nba
type: Opaque
data:
  # API Keys (base64 encoded)
  GOOGLE_API_KEY_NBA_MCP_SYNTHESIS_WORKFLOW: <base64-encoded-google-api-key>
  ANTHROPIC_API_KEY_NBA_MCP_SYNTHESIS_WORKFLOW: <base64-encoded-anthropic-api-key>
  DEEPSEEK_API_KEY_NBA_MCP_SYNTHESIS_WORKFLOW: <base64-encoded-deepseek-api-key>
  OPENAI_API_KEY_NBA_MCP_SYNTHESIS_WORKFLOW: <base64-encoded-openai-api-key>

  # Database Credentials
  DB_PASSWORD_NBA_MCP_SYNTHESIS_WORKFLOW: <base64-encoded-db-password>
  DB_HOST_NBA_MCP_SYNTHESIS_WORKFLOW: <base64-encoded-db-host>
  DB_PORT_NBA_MCP_SYNTHESIS_WORKFLOW: <base64-encoded-db-port>

  # Integration Credentials
  SLACK_WEBHOOK_URL_BIG_CAT_BETS_GLOBAL_WORKFLOW: <base64-encoded-slack-webhook-url>
  LINEAR_API_KEY_BIG_CAT_BETS_GLOBAL_WORKFLOW: <base64-encoded-linear-api-key>
  LINEAR_TEAM_ID_BIG_CAT_BETS_GLOBAL_WORKFLOW: <base64-encoded-linear-team-id>
  LINEAR_PROJECT_ID_BIG_CAT_BETS_GLOBAL_WORKFLOW: <base64-encoded-linear-project-id>
---
apiVersion: v1
kind: Secret
metadata:
  name: nba-mcp-synthesis-db-secrets
  namespace: nba-mcp-synthesis
  labels:
    app: nba-mcp-synthesis
    environment: production
    project: nba-mcp-synthesis
    sport: nba
    component: database
type: Opaque
data:
  # PostgreSQL Credentials
  POSTGRES_DB: bmJhX21jcF9zeW50aGVzaXM=
  POSTGRES_USER: bmJhX21jcF91c2Vy
  POSTGRES_PASSWORD: <base64-encoded-postgres-password>
---
apiVersion: v1
kind: Secret
metadata:
  name: nba-mcp-synthesis-redis-secrets
  namespace: nba-mcp-synthesis
  labels:
    app: nba-mcp-synthesis
    environment: production
    project: nba-mcp-synthesis
    sport: nba
    component: redis
type: Opaque
data:
  # Redis Credentials
  REDIS_PASSWORD: <base64-encoded-redis-password>
  REDIS_HOST: bmJhLW1jcC1yZWRpcw==
  REDIS_PORT: NjM3OQ==


