-- ==============================================================================
-- Betting Tables - Arbitrage Opportunities & Recommendations
-- ==============================================================================
--
-- These tables store betting opportunities detected by the automation system:
--   1. arbitrage_opportunities: Guaranteed profit across multiple bookmakers
--   2. betting_recommendations: Positive EV bets from ML predictions + live odds
--
-- Author: NBA MCP Synthesis Team
-- Date: 2025-01-05
--
-- Usage:
--   This script runs automatically when PostgreSQL container initializes
--   Depends on: 01_games_table.sql (for game references)
--
-- ==============================================================================

-- Drop existing tables if they exist (for clean reinitialization)
DROP TABLE IF EXISTS arbitrage_opportunities CASCADE;
DROP TABLE IF EXISTS betting_recommendations CASCADE;

-- ==============================================================================
-- Arbitrage Opportunities Table
-- ==============================================================================
--
-- Stores detected arbitrage opportunities across multiple bookmakers
--
-- This table tracks guaranteed profit opportunities where you can bet on all
-- outcomes at different bookmakers and profit regardless of the result.
--
-- ==============================================================================

CREATE TABLE arbitrage_opportunities (
    arb_id SERIAL PRIMARY KEY,

    -- Event identification
    event_id VARCHAR(255) NOT NULL,
    game_date DATE NOT NULL,
    matchup VARCHAR(255) NOT NULL,
    market_type VARCHAR(50) NOT NULL DEFAULT 'h2h',

    -- Bookmaker A (best odds for outcome A)
    bookmaker_a VARCHAR(100) NOT NULL,
    side_a VARCHAR(100) NOT NULL,
    odds_a_american DECIMAL(10, 2) NOT NULL,
    odds_a_decimal DECIMAL(10, 4) NOT NULL,

    -- Bookmaker B (best odds for outcome B)
    bookmaker_b VARCHAR(100) NOT NULL,
    side_b VARCHAR(100) NOT NULL,
    odds_b_american DECIMAL(10, 2) NOT NULL,
    odds_b_decimal DECIMAL(10, 4) NOT NULL,

    -- Arbitrage calculations
    arb_percentage DECIMAL(6, 4) NOT NULL,  -- e.g., 0.0180 = 1.8% guaranteed profit
    total_implied_prob DECIMAL(6, 4) NOT NULL,  -- e.g., 0.9820 = 98.2% (< 100% = arb exists)

    -- Recommended stakes (for $1000 total investment)
    stake_a DECIMAL(10, 2),
    stake_b DECIMAL(10, 2),
    guaranteed_profit DECIMAL(10, 2),

    -- Metadata
    detected_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP,  -- When odds likely to change (detected_at + 5 minutes)
    is_valid BOOLEAN DEFAULT TRUE,  -- False if arbitrage closed
    validation_note TEXT,  -- Reason if invalidated

    -- Notification tracking
    email_sent BOOLEAN DEFAULT FALSE,
    sms_sent BOOLEAN DEFAULT FALSE,
    notification_sent_at TIMESTAMP,

    -- Constraints
    CONSTRAINT valid_arb_percentage CHECK (arb_percentage > 0),
    CONSTRAINT different_bookmakers CHECK (bookmaker_a != bookmaker_b)
);

-- Indexes for performance
CREATE INDEX idx_arb_game_date ON arbitrage_opportunities(game_date);
CREATE INDEX idx_arb_event_id ON arbitrage_opportunities(event_id);
CREATE INDEX idx_arb_detected_at ON arbitrage_opportunities(detected_at DESC);
CREATE INDEX idx_arb_valid ON arbitrage_opportunities(is_valid) WHERE is_valid = TRUE;
CREATE INDEX idx_arb_percentage ON arbitrage_opportunities(arb_percentage DESC);

-- Comments
COMMENT ON TABLE arbitrage_opportunities IS 'Tracks detected arbitrage betting opportunities across multiple bookmakers';
COMMENT ON COLUMN arbitrage_opportunities.arb_percentage IS 'Guaranteed profit percentage (0.0180 = 1.8% profit)';
COMMENT ON COLUMN arbitrage_opportunities.total_implied_prob IS 'Sum of implied probabilities (< 1.0 indicates arbitrage)';
COMMENT ON COLUMN arbitrage_opportunities.is_valid IS 'FALSE if odds have moved and arbitrage no longer exists';
COMMENT ON COLUMN arbitrage_opportunities.expires_at IS 'Expected expiration time (typically 5 minutes from detection)';

-- ==============================================================================
-- Betting Recommendations Table
-- ==============================================================================
--
-- Stores daily betting recommendations generated by the automation system
--
-- This table tracks positive EV betting opportunities identified by combining
-- ML predictions with live odds, sized using the Kelly Criterion.
--
-- ==============================================================================

CREATE TABLE betting_recommendations (
    rec_id SERIAL PRIMARY KEY,

    -- Event identification
    game_id VARCHAR(255) NOT NULL,
    event_id VARCHAR(255),
    game_date DATE NOT NULL,
    matchup VARCHAR(255) NOT NULL,
    game_time VARCHAR(100),  -- e.g., "7:00 PM ET"

    -- Bet details
    bet_side VARCHAR(100) NOT NULL,  -- Team name or "Over"/"Under"
    bet_type VARCHAR(50) NOT NULL,  -- 'home', 'away', 'over', 'under', 'spread'
    market_type VARCHAR(50) NOT NULL DEFAULT 'h2h',

    -- Odds information
    bookmaker VARCHAR(100) NOT NULL,
    odds_american DECIMAL(10, 2) NOT NULL,
    odds_decimal DECIMAL(10, 4) NOT NULL,

    -- ML prediction
    ml_prob DECIMAL(6, 4) NOT NULL,  -- Model's probability (0-1)
    confidence DECIMAL(6, 4),  -- Model confidence score (0-1)

    -- Edge calculation
    implied_prob DECIMAL(6, 4) NOT NULL,  -- Market implied probability
    edge DECIMAL(6, 4) NOT NULL,  -- ml_prob - implied_prob
    ev DECIMAL(10, 4) NOT NULL,  -- Expected value: (ml_prob * odds_decimal) - 1

    -- Kelly Criterion sizing
    kelly_raw DECIMAL(6, 4),  -- Raw Kelly fraction
    kelly_fraction DECIMAL(6, 4) NOT NULL,  -- Adjusted Kelly fraction (capped)
    recommended_stake DECIMAL(10, 2) NOT NULL,  -- Recommended bet size in dollars
    bankroll DECIMAL(10, 2),  -- Bankroll at time of recommendation

    -- Portfolio context
    daily_batch_id VARCHAR(100),  -- Links recommendations from same daily run
    total_daily_stake DECIMAL(10, 2),  -- Total stake across all daily bets
    total_daily_ev DECIMAL(10, 4),  -- Total EV across all daily bets
    bankroll_exposure DECIMAL(6, 4),  -- % of bankroll exposed

    -- Outcome tracking
    result VARCHAR(50),  -- 'win', 'loss', 'push', 'pending', 'cancelled'
    actual_stake DECIMAL(10, 2),  -- Actual amount bet (may differ from recommended)
    actual_bookmaker VARCHAR(100),  -- Where bet was actually placed
    payout DECIMAL(10, 2),  -- Actual payout if won
    profit_loss DECIMAL(10, 2),  -- Final P&L for this bet

    -- Metadata
    generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    bet_placed_at TIMESTAMP,
    result_recorded_at TIMESTAMP,

    -- Notification tracking
    email_sent BOOLEAN DEFAULT FALSE,
    sms_sent BOOLEAN DEFAULT FALSE,
    notification_sent_at TIMESTAMP,

    -- Notes and flags
    notes TEXT,
    is_critical BOOLEAN DEFAULT FALSE,  -- True if edge > 10% (critical alert)
    is_paper_trade BOOLEAN DEFAULT TRUE,  -- True if paper trading, False if real money

    -- Constraints
    CONSTRAINT valid_edge CHECK (edge >= 0),
    CONSTRAINT valid_kelly CHECK (kelly_fraction >= 0 AND kelly_fraction <= 1),
    CONSTRAINT valid_ml_prob CHECK (ml_prob >= 0 AND ml_prob <= 1),
    CONSTRAINT valid_result CHECK (result IN ('win', 'loss', 'push', 'pending', 'cancelled', NULL))
);

-- Indexes for performance
CREATE INDEX idx_rec_game_date ON betting_recommendations(game_date DESC);
CREATE INDEX idx_rec_event_id ON betting_recommendations(event_id);
CREATE INDEX idx_rec_generated_at ON betting_recommendations(generated_at DESC);
CREATE INDEX idx_rec_daily_batch ON betting_recommendations(daily_batch_id);
CREATE INDEX idx_rec_result ON betting_recommendations(result);
CREATE INDEX idx_rec_edge ON betting_recommendations(edge DESC);
CREATE INDEX idx_rec_is_critical ON betting_recommendations(is_critical) WHERE is_critical = TRUE;
CREATE INDEX idx_rec_paper_trade ON betting_recommendations(is_paper_trade);

-- Comments
COMMENT ON TABLE betting_recommendations IS 'Daily betting recommendations combining ML predictions with live odds and Kelly sizing';
COMMENT ON COLUMN betting_recommendations.edge IS 'Betting edge: ml_prob - implied_prob (positive = +EV)';
COMMENT ON COLUMN betting_recommendations.kelly_fraction IS 'Kelly Criterion bet size as fraction of bankroll (capped at 5%)';
COMMENT ON COLUMN betting_recommendations.daily_batch_id IS 'UUID linking all recommendations from same daily run';
COMMENT ON COLUMN betting_recommendations.is_critical IS 'TRUE if edge >= 10% (triggers SMS alert)';
COMMENT ON COLUMN betting_recommendations.is_paper_trade IS 'FALSE when transitioning to real money betting';

-- ==============================================================================
-- Example Queries
-- ==============================================================================

-- ===== ARBITRAGE OPPORTUNITIES =====

-- Find all valid arbitrage opportunities for today
-- SELECT
--     matchup,
--     bookmaker_a,
--     side_a,
--     odds_a_american,
--     bookmaker_b,
--     side_b,
--     odds_b_american,
--     arb_percentage,
--     guaranteed_profit
-- FROM arbitrage_opportunities
-- WHERE game_date = CURRENT_DATE
--   AND is_valid = TRUE
--   AND expires_at > NOW()
-- ORDER BY arb_percentage DESC;

-- ===== BETTING RECOMMENDATIONS =====

-- 1. Today's top picks (ordered by edge)
-- SELECT
--     matchup,
--     bet_side,
--     odds_american,
--     edge,
--     recommended_stake,
--     bookmaker
-- FROM betting_recommendations
-- WHERE game_date = CURRENT_DATE
--   AND result IS NULL
-- ORDER BY edge DESC
-- LIMIT 3;

-- 2. Performance analysis (last 30 days)
-- SELECT
--     COUNT(*) as total_bets,
--     COUNT(*) FILTER (WHERE result = 'win') as wins,
--     COUNT(*) FILTER (WHERE result = 'loss') as losses,
--     SUM(profit_loss) as total_profit,
--     AVG(edge) as avg_edge,
--     SUM(actual_stake) as total_staked
-- FROM betting_recommendations
-- WHERE game_date >= CURRENT_DATE - INTERVAL '30 days'
--   AND result IN ('win', 'loss');

-- 3. Critical alerts (high edge opportunities)
-- SELECT
--     matchup,
--     bet_side,
--     edge,
--     recommended_stake,
--     generated_at
-- FROM betting_recommendations
-- WHERE is_critical = TRUE
--   AND game_date = CURRENT_DATE
-- ORDER BY edge DESC;

-- 4. Calibration analysis (compare predicted vs actual win rate)
-- SELECT
--     ROUND(ml_prob, 1) as predicted_prob,
--     COUNT(*) as n_bets,
--     COUNT(*) FILTER (WHERE result = 'win') * 1.0 / COUNT(*) as actual_win_rate,
--     ROUND(ml_prob, 1) - (COUNT(*) FILTER (WHERE result = 'win') * 1.0 / COUNT(*)) as calibration_error
-- FROM betting_recommendations
-- WHERE result IN ('win', 'loss')
-- GROUP BY ROUND(ml_prob, 1)
-- ORDER BY predicted_prob DESC;

-- ==============================================================================
-- End of schema
-- ==============================================================================
