#!/bin/bash

# session_start.sh - Generate compact current-session.md for optimal context usage
# Usage: ./scripts/session_start.sh [--new-session]

set -e

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Detect project root (look for .ai directory)
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_ROOT"

echo -e "${BLUE}🚀 Starting New Session${NC}"
echo "================================"

# Create .ai directory if it doesn't exist
mkdir -p .ai/daily .ai/monthly .ai/permanent .ai/archive

# Get today's date
TODAY=$(date +%Y-%m-%d)
NOW=$(date +%Y-%m-%d\ %H:%M:%S)

# Count existing sessions today
SESSION_NUM=$(ls -1 .ai/daily/${TODAY}-session-*.md 2>/dev/null | wc -l | tr -d ' ')
SESSION_NUM=$((SESSION_NUM + 1))

# Create new daily session file if --new-session flag
if [ "$1" == "--new-session" ]; then
    DAILY_FILE=".ai/daily/${TODAY}-session-${SESSION_NUM}.md"
    echo -e "${GREEN}📝 Creating new daily session file: ${DAILY_FILE}${NC}"

    # Copy template or create basic structure
    if [ -f ".ai/daily/template.md" ]; then
        cp .ai/daily/template.md "$DAILY_FILE"
        # Replace template placeholders
        sed -i.bak "s/YYYY-MM-DD/${TODAY}/g" "$DAILY_FILE"
        sed -i.bak "s/Session**: N/Session**: ${SESSION_NUM}/g" "$DAILY_FILE"
        rm "${DAILY_FILE}.bak" 2>/dev/null || true
    fi
fi

# Generate current-session.md
echo -e "${BLUE}📊 Generating current-session.md...${NC}"

# Get git status info
GIT_STATUS=$(git status --short 2>/dev/null || echo "No git repo")
MODIFIED_COUNT=$(echo "$GIT_STATUS" | grep -c '^.M' || echo "0")
STAGED_COUNT=$(echo "$GIT_STATUS" | grep -c '^M' || echo "0")
UNTRACKED_COUNT=$(echo "$GIT_STATUS" | grep -c '^??' || echo "0")

# Get last 5 commits (compact format)
RECENT_COMMITS=$(git log --oneline -5 --no-decorate 2>/dev/null || echo "No commits")

# Get current branch
CURRENT_BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")

# Get last session file
LAST_SESSION=$(ls -t .ai/daily/*.md 2>/dev/null | head -1)
LAST_SESSION_SUMMARY=""
if [ -n "$LAST_SESSION" ]; then
    # Extract "Next Session" section from last session if it exists
    LAST_SESSION_SUMMARY=$(grep -A 5 "## 🚀 Next Session" "$LAST_SESSION" 2>/dev/null | head -10 || echo "")
fi

# Check for PROJECT_MASTER_TRACKER.md metrics
if [ -f "PROJECT_MASTER_TRACKER.md" ]; then
    TOOLS_REGISTERED=$(grep -o "Total MCP Tools.*: [0-9]*" PROJECT_MASTER_TRACKER.md | head -1 || echo "Unknown")
    OVERALL_PROGRESS=$(grep -o "Overall.*: [0-9]*%" PROJECT_MASTER_TRACKER.md | head -1 || echo "Unknown")
else
    TOOLS_REGISTERED="Not tracked"
    OVERALL_PROGRESS="Not tracked"
fi

# Generate compact current-session.md
cat > .ai/current-session.md << EOF
# Current Session State

**Generated**: ${NOW}
**Branch**: ${CURRENT_BRANCH}
**Session**: ${SESSION_NUM} (${TODAY})

---

## 🎯 Active Work

**Current Task**: Ready to continue work
**Status**: Awaiting instructions

### Quick Stats
- Modified files: ${MODIFIED_COUNT}
- Staged files: ${STAGED_COUNT}
- Untracked files: ${UNTRACKED_COUNT}

---

## 📝 Recent Activity

### Last 5 Commits
\`\`\`
${RECENT_COMMITS}
\`\`\`

### Uncommitted Changes
\`\`\`
$(echo "$GIT_STATUS" | head -15)
$(if [ $(echo "$GIT_STATUS" | wc -l) -gt 15 ]; then echo "... ($(( $(echo "$GIT_STATUS" | wc -l) - 15 )) more)"; fi)
\`\`\`

---

## 📊 Project Status

**${TOOLS_REGISTERED}**
**${OVERALL_PROGRESS}**

---

## 🚀 Next Immediate Actions

${LAST_SESSION_SUMMARY:-No previous session notes available}

---

## 🔍 Context

**Last Session**: $(basename "$LAST_SESSION" .md 2>/dev/null || echo "None")
**Current Session**: New session starting at ${NOW}

**Key Files**:
- PROJECT_MASTER_TRACKER.md - Overall progress tracking
- docs/plans/MASTER_PLAN.md - Strategic planning
- .ai/daily/${TODAY}-session-${SESSION_NUM}.md - Today's detailed log

---

**Auto-Generated**: This file is regenerated by \`scripts/session_start.sh\`
**Manual Edit**: Avoid manual edits - use session scripts instead
**Context Cost**: ~100 tokens (vs 5000+ reading multiple files)
EOF

echo -e "${GREEN}✅ current-session.md generated successfully${NC}"
echo ""
echo -e "${BLUE}📋 Session Summary:${NC}"
echo "  Branch: ${CURRENT_BRANCH}"
echo "  Modified: ${MODIFIED_COUNT} | Staged: ${STAGED_COUNT} | Untracked: ${UNTRACKED_COUNT}"
echo "  Last session: $(basename "$LAST_SESSION" .md 2>/dev/null || echo "None")"
echo ""
echo -e "${YELLOW}💡 Quick Start:${NC}"
echo "  Read context:  cat .ai/current-session.md"
echo "  View details:  cat ${LAST_SESSION:-PROJECT_MASTER_TRACKER.md}"
echo "  New session:   ./scripts/session_start.sh --new-session"
echo ""
echo -e "${GREEN}🎯 Ready to code!${NC}"
